version: "3"
services:
  9cc:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/9cc
    working_dir: /9cc
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
